### ISSUE TITLE
Weather alerts shown are for different country

### ISSUE THREAD

**Issue by davey-p1** [PranshulGG/WeatherMaster#127]
Hi. I am seeing a weather alert for the UK, yet my location is set to Republic of Ireland.
Please let me know if you require any further information.
Thanks

**Comment by PranshulGG** [comment]
Can you share a screenshot of the alert?

**Comment by davey-p1** [comment]
![Screenshot_2024-11-17-11-16-48-30](https://github.com/user-attachments/assets/1dd48ebf-1c2f-4c5e-8b90-a9475b4c9860)
Of course.    Thanks.

**Comment by PranshulGG** [comment]
This issue is usually difficult to fix because it's the API returning the data.

A few reasons could be:

- Alert API pulling data from a UK-centric service, which could include alerts for the UK by default.
- The location might be close to the UK, causing the app to receive alerts for nearby regions.
