### ISSUE TITLE
Rain effect enhance

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#211]
### Problem Statement

Could you please make the rain effect even better by having it fall in different spots throughout the picture and on Frogie's leaf (not through Frogie)? That would be awesome!

### Proposed Solution

1. Make the rain effect fall in different spots throughout the picture.
2. Don't let water droplets fall through the Frogie's leaf.

### Additional Context

![Screenshot_2024-12-07-12-46-56-790_com example weathermaster](https://github.com/user-attachments/assets/d62bc49b-7261-4512-9726-1a4752a8544b)

**Comment by PranshulGG** [comment]
Making the rainfall happen in specific areas, like Frogie's leaf, is almost impossible with the current setup. The image is flat and changes each time, so there are no separate elements to interact with. The rain effect is applied as a canvas animation that adapts to the screen size, so controlling specific areas would be very tricky and inconsistent across devices. I'll keep this issue open, but the priority is low since this feature isn't really important and there are more important things to fix.
