### ISSUE TITLE
wrong unit in textual report

### ISSUE THREAD

**Issue by Der-Flip** [PranshulGG/WeatherMaster#28]
hi, great app, beautifully designed.

In the text report the precipitation unit doesn't seem to be affected by the selected unit in the settings; I have it set to mm, but it's still being reported in inches. [screenshot for clarification](https://github.com/user-attachments/assets/fcf82251-7a62-4bca-a845-a229b0374579)

while we're at it, maybe ad the unit to the degrees (° isn't really the unit. so probably best to add the C or F).

**Comment by PranshulGG** [comment]
I know about this issue—I forgot to add a function to convert it to mm, as it returns in inches by default.

As for the `°` symbol (without `°C` or `°F`), I chose that because it looks better, and sometimes the text alignment gets messed up. I don't think it's necessary since you already know which setting you have applied.
